// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Blog {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  published_on: string;
  hero_image?: string;
  listing_image?: string;
  content?: PortableTextBlock[];
  reading_time?: number;
  authors?: unknown;
  tags?: unknown;
  hide_hero?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Changelog {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  published_on: string;
  hero_image?: string;
  listing_image?: string;
  content?: PortableTextBlock[];
  reading_time?: number;
  category?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    blog: Blog;
    changelog: Changelog;
  }
}