[build]
  publish = ".ouput"
  command = "pnpm run deploy && PORT=3000 node /opt/build/repo/.output/index.js"

[functions]
  directory = "functions"
  node_bundler = "none"
  included_files = ["functions/**"]
