export const BlogTags = {
  AI: 'ai',
  ANNOUNCEMENT: 'announcement',
  ARCHITECTURE: 'architecture',
  CASE_STUDY: 'case-study',
  CDN: 'cdn',
  CLOUD: 'cloud',
  COMMUNITY: 'community',
  DEPLOYMENT: 'deployment',
  DEVOPS: 'devops',
  DX: 'dx',
  EDGE: 'edge',
  ENGINEERING: 'engineering',
  ENTERPRISE: 'enterprise',
  INCIDENT_RESPONSE: 'incident-response',
  LAUNCH_WEEK: 'launch-week',
  MICRO_FRONTENDS: 'micro-frontends',
  MOBILE: 'mobile',
  MODULE_FEDERATION: 'module-federation',
  OPS: 'ops',
  OUTAGE: 'outage',
  POLYCLOUD: 'polycloud',
  PRODUCT: 'product',
  REACT_NATIVE: 'react-native',
  SCALABILITY: 'scalability',
  TUTORIAL: 'tutorial',
  WEB: 'web',
} as const;

export type BlogTag = (typeof BlogTags)[keyof typeof BlogTags];

export const tagLabels: Record<BlogTag, string> = {
  [BlogTags.AI]: 'AI',
  [BlogTags.ANNOUNCEMENT]: 'Announcement',
  [BlogTags.ARCHITECTURE]: 'Architecture',
  [BlogTags.CASE_STUDY]: 'Case Study',
  [BlogTags.CDN]: 'CDN',
  [BlogTags.CLOUD]: 'Cloud',
  [BlogTags.COMMUNITY]: 'Community',
  [BlogTags.DEPLOYMENT]: 'Deployment',
  [BlogTags.DEVOPS]: 'DevOps',
  [BlogTags.DX]: 'DX',
  [BlogTags.EDGE]: 'Edge',
  [BlogTags.ENGINEERING]: 'Engineering',
  [BlogTags.ENTERPRISE]: 'Enterprise',
  [BlogTags.INCIDENT_RESPONSE]: 'Incident Response',
  [BlogTags.LAUNCH_WEEK]: 'Launch Week',
  [BlogTags.MICRO_FRONTENDS]: 'Micro Frontends',
  [BlogTags.MOBILE]: 'Mobile',
  [BlogTags.MODULE_FEDERATION]: 'Module Federation',
  [BlogTags.OPS]: 'Ops',
  [BlogTags.OUTAGE]: 'Outage',
  [BlogTags.POLYCLOUD]: 'Polycloud',
  [BlogTags.PRODUCT]: 'Product',
  [BlogTags.REACT_NATIVE]: 'React Native',
  [BlogTags.SCALABILITY]: 'Scalability',
  [BlogTags.TUTORIAL]: 'Tutorial',
  [BlogTags.WEB]: 'Web',
};
