export const BlogTags = {
  AI: 'ai',
  WEB: 'web',
  MOBILE: 'mobile',
  CLOUD: 'cloud',
  DEVOPS: 'devops',
  ARCHITECTURE: 'architecture',
  CASE_STUDY: 'case-study',
  ANNOUNCEMENT: 'announcement',
  REACT_NATIVE: 'react-native',
  DEPLOYMENT: 'deployment',
  COMMUNITY: 'community',
  ENGINEERING: 'engineering',
  ENTERPRISE: 'enterprise',
  LAUNCH_WEEK: 'launch-week',
  MICRO_FRONTENDS: 'micro-frontends',
  OPS: 'ops',
  POLYCLOUD: 'polycloud',
  PRODUCT: 'product',
  TUTORIAL: 'tutorial',
} as const;

export type BlogTag = typeof BlogTags[keyof typeof BlogTags];

export const tagLabels: Record<BlogTag, string> = {
  [BlogTags.AI]: 'AI',
  [BlogTags.WEB]: 'Web',
  [BlogTags.MOBILE]: 'Mobile',
  [BlogTags.CLOUD]: 'Cloud',
  [BlogTags.DEVOPS]: 'DevOps',
  [BlogTags.ARCHITECTURE]: 'Architecture',
  [BlogTags.CASE_STUDY]: 'Case Study',
  [BlogTags.ANNOUNCEMENT]: 'Announcement',
  [BlogTags.REACT_NATIVE]: 'React Native',
  [BlogTags.DEPLOYMENT]: 'Deployment',
  [BlogTags.COMMUNITY]: 'Community',
  [BlogTags.ENGINEERING]: 'Engineering',
  [BlogTags.ENTERPRISE]: 'Enterprise',
  [BlogTags.LAUNCH_WEEK]: 'Launch Week',
  [BlogTags.MICRO_FRONTENDS]: 'Micro Frontends',
  [BlogTags.OPS]: 'Ops',
  [BlogTags.POLYCLOUD]: 'Polycloud',
  [BlogTags.PRODUCT]: 'Product',
  [BlogTags.TUTORIAL]: 'Tutorial',
};